#!/bin/bash


selection=$(echo \
'Brave
Chromium
Discord
Drawing
Firefox
Kdenlive
Krita
Nautilus
ST
URXVT
VS-Code'\
 | rofi -dmenu run -theme dmenu.rasi -p 'RUN' -i)

[[ -z $selection ]] && exit



if [[ $selection = 'Chrome' ]]; then
	exec google-chrome-stable
elif [[ $selection = 'Firefox' ]]; then
	exec firefox
elif [[ $selection = 'Discord' ]]; then
	exec discord
elif [[ $selection = 'RXVT' ]]; then
	exec urxvt
elif [[ $selection = 'ST' ]]; then
	exec st
elif [[ $selection = 'VS-Code' ]]; then
	exec code
elif [[ $selection = 'Brave' ]]; then
	exec brave
elif [[ $selection = 'Nautilus' ]]; then
	exec nautilus
elif [[ $selection = 'Kdenlive' ]]; then
	exec kdenlive
elif [[ $selection = 'Krita' ]]; then
	exec krita
elif [[ $selection = 'Drawing' ]]; then
	exec drawing
fi
