#!/bin/bash


selection=$(echo \
'Brave
Chromium
Discord
Drawing
Firefox
Kdenlive
Krita
Nautilus
ST
URXVT
Phpstorm
Pop
DBeaver
TablePlus
Slack
VS-Code'\
 | rofi -dmenu run -theme survive.rasi -p 'run' -i)

[[ -z $selection ]] && exit



if [[ $selection = 'Chrome' ]]; then
	exec google-chrome-stable
elif [[ $selection = 'Firefox' ]]; then
	exec firefox
elif [[ $selection = 'Discord' ]]; then
	exec discord
elif [[ $selection = 'RXVT' ]]; then
	exec urxvt
elif [[ $selection = 'ST' ]]; then
	exec st
elif [[ $selection = 'VS-Code' ]]; then
	exec code
elif [[ $selection = 'Brave' ]]; then
	exec brave
elif [[ $selection = 'Chromium' ]]; then
	exec chromium
elif [[ $selection = 'Phpstorm' ]]; then
	exec $HOME/doc/phpstorm/bin/phpstorm.sh
elif [[ $selection = 'Nautilus' ]]; then
	exec nautilus
elif [[ $selection = 'Kdenlive' ]]; then
	exec kdenlive
elif [[ $selection = 'Krita' ]]; then
	exec krita
elif [[ $selection = 'Drawing' ]]; then
	exec drawing
elif [[ $selection = 'Pop' ]]; then
	exec pop
elif [[ $selection = 'DBeaver' ]]; then
	exec dbeaver
elif [[ $selection = 'TablePlus' ]]; then
	exec tableplus
elif [[ $selection = 'Slack' ]]; then
	exec slack
fi
